# Generated by Django 5.2.7 on 2025-11-04 00:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('technologies', models.CharField(max_length=300, verbose_name='Технологии (через запятую)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Изображение')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub ссылка')),
                ('live_url', models.URLField(blank=True, verbose_name='Live демо')),
                ('download_url', models.URLField(blank=True, verbose_name='Ссылка для скачивания')),
                ('stars', models.IntegerField(default=0, verbose_name='Звезды')),
                ('forks', models.IntegerField(default=0, verbose_name='Форки')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++'), ('go', 'Go'), ('rust', 'Rust'), ('php', 'PHP'), ('ruby', 'Ruby'), ('swift', 'Swift'), ('kotlin', 'Kotlin')], default='python', max_length=20, verbose_name='Язык программирования')),
                ('language_color', models.CharField(default='#3572A5', max_length=7, verbose_name='Цвет языка')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_date'],
            },
        ),
    ]
