# Generated by Django 5.2.7 on 2025-11-04 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='language',
        ),
        migrations.RemoveField(
            model_name='project',
            name='language_color',
        ),
    ]
