# Generated by Django 5.2.7 on 2025-11-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_project_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_api_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='GitHub API URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='last_github_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация с GitHub'),
        ),
    ]
